#!/usr/bin/env python3
"""Generate Memo Pixel 16 from the pinned, OFL-licensed Unifont glyph source."""

import gzip
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def character_set():
    """GB2312, ASCII and selected punctuation; storage still accepts Unicode."""
    characters = set(range(32, 127)) | set(range(0x2000, 0x2070))
    characters |= set(range(0x3000, 0x3040)) | {0x00B7, 0xFFFD}
    for lead in range(0xA1, 0xF8):
        for trail in range(0xA1, 0xFF):
            try:
                characters.add(ord(bytes([lead, trail]).decode("gb2312")))
            except UnicodeDecodeError:
                pass
    return characters


def numbers(sequence, pattern):
    return ",\n".join(
        ",".join(pattern % value for value in sequence[index:index + 24])
        for index in range(0, len(sequence), 24)
    )


def main():
    source_path = ROOT / "assets/fonts/unifont-17.0.05.hex.gz"
    with gzip.open(source_path, "rt", encoding="ascii") as source_file:
        source = {
            int(code, 16): bytes.fromhex(bitmap)
            for code, bitmap in (line.split(":") for line in source_file)
        }
    codes = sorted(character_set() & source.keys())
    data = bytearray()
    descriptors = ["{0,0,0,0,0,0}"]
    offsets = []
    for code in codes:
        glyph = source[code]
        width = len(glyph) // 2
        descriptors.append("{%d,%d,%d,16,0,-2}" % (len(data), width * 16, width))
        data.extend(glyph)
        offsets.append(code - 32)
    s='''/* Generated by tools/build_memo_font.py. Memo Pixel 16, derived from GNU Unifont.
 * Copyright GNU Unifont contributors. SIL OFL 1.1; see assets/fonts/ licenses. */
#include "lvgl.h"
static const uint8_t bitmap[]={\n'''+numbers(list(data),'0x%02x')+'''};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[]={\n'''+',\n'.join(descriptors)+'''};
static const uint16_t unicode_list[]={\n'''+numbers(offsets,'%d')+'''};
static const lv_font_fmt_txt_cmap_t cmaps[]={
{.range_start=32,.range_length=65504,.glyph_id_start=1,.unicode_list=unicode_list,
 .glyph_id_ofs_list=NULL,.list_length='''+str(len(codes))+''',.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};
static const lv_font_fmt_txt_dsc_t dsc={.glyph_bitmap=bitmap,.glyph_dsc=glyphs,
 .cmaps=cmaps,.bpp=1,.cmap_num=1,.bitmap_format=0};
const lv_font_t memo_font_16={.get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,
 .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,.line_height=18,.base_line=3,
 .dsc=&dsc,.static_bitmap=1};
'''
    (ROOT / "main/memo_font_16.c").write_text(s, encoding="utf-8")
    print(f"{len(codes)} glyphs, {len(data)} bitmap bytes")


if __name__ == "__main__":
    main()
